sudo: required
services:
  - docker

before_install:
  - docker build -t richg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run richg/react-test npm test -- --coverage

after_success:
  - docker build -t richg/fib-client ./client
  - docker build -t richg/fib-server ./server
  - docker build -t richg/fib-nginx ./nginx
  - docker build -t richg/fib-worker ./worker
